services:
  # Serviço da Aplicação (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  # Serviço do Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # Serviço do Banco de Dados (PostgreSQL)
  pgsql:
    image: postgres:16-alpine
    container_name: laravel_pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql_data:/var/lib/postgresql/data  # <-- 1. Use um volume nomeado aqui
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
    
volumes:
  pgsql_data:
    driver: local